<?php

namespace Proxies\__CG__\Almacigos\VentaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pedido extends \Almacigos\VentaBundle\Entity\Pedido implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'id', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'cantidadSolicitada', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'neto', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'total', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'fechaDespacho', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'notaVenta', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'producto', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'siembras');
        }

        return array('__isInitialized__', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'id', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'cantidadSolicitada', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'neto', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'total', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'fechaDespacho', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'notaVenta', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'producto', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\Pedido' . "\0" . 'siembras');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pedido $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeto($neto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeto', array($neto));

        return parent::setNeto($neto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeto', array());

        return parent::getNeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaDespacho($fechaDespacho)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaDespacho', array($fechaDespacho));

        return parent::setFechaDespacho($fechaDespacho);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaDespacho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaDespacho', array());

        return parent::getFechaDespacho();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotaVenta(\Almacigos\VentaBundle\Entity\NotaVenta $notaVenta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotaVenta', array($notaVenta));

        return parent::setNotaVenta($notaVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotaVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotaVenta', array());

        return parent::getNotaVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducto(\Almacigos\VentaBundle\Entity\Producto $producto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducto', array($producto));

        return parent::setProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducto', array());

        return parent::getProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addSiembra(\Almacigos\SiembraBundle\Entity\Siembra $siembras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSiembra', array($siembras));

        return parent::addSiembra($siembras);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSiembra(\Almacigos\SiembraBundle\Entity\Siembra $siembras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSiembra', array($siembras));

        return parent::removeSiembra($siembras);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiembras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiembras', array());

        return parent::getSiembras();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadSolicitada($cantidadSolicitada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadSolicitada', array($cantidadSolicitada));

        return parent::setCantidadSolicitada($cantidadSolicitada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadSolicitada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadSolicitada', array());

        return parent::getCantidadSolicitada();
    }

}
