<?php

namespace Proxies\__CG__\Almacigos\SiembraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Siembra extends \Almacigos\SiembraBundle\Entity\Siembra implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'id', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'siembra', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'dias', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'cantidadBandejas', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'cantidadSembrar', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'cantidadEsperada', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'pedido', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'bandeja');
        }

        return array('__isInitialized__', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'id', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'siembra', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'dias', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'cantidadBandejas', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'cantidadSembrar', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'cantidadEsperada', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'pedido', '' . "\0" . 'Almacigos\\SiembraBundle\\Entity\\Siembra' . "\0" . 'bandeja');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Siembra $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiembra($siembra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiembra', array($siembra));

        return parent::setSiembra($siembra);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiembra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiembra', array());

        return parent::getSiembra();
    }

    /**
     * {@inheritDoc}
     */
    public function setDias($dias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDias', array($dias));

        return parent::setDias($dias);
    }

    /**
     * {@inheritDoc}
     */
    public function getDias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDias', array());

        return parent::getDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadBandejas($cantidadBandejas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadBandejas', array($cantidadBandejas));

        return parent::setCantidadBandejas($cantidadBandejas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadBandejas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadBandejas', array());

        return parent::getCantidadBandejas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadSembrar($cantidadSembrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadSembrar', array($cantidadSembrar));

        return parent::setCantidadSembrar($cantidadSembrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadSembrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadSembrar', array());

        return parent::getCantidadSembrar();
    }

    /**
     * {@inheritDoc}
     */
    public function setPedido(\Almacigos\VentaBundle\Entity\Pedido $pedido = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPedido', array($pedido));

        return parent::setPedido($pedido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPedido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedido', array());

        return parent::getPedido();
    }

    /**
     * {@inheritDoc}
     */
    public function setBandeja(\Almacigos\SiembraBundle\Entity\Bandeja $bandeja = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBandeja', array($bandeja));

        return parent::setBandeja($bandeja);
    }

    /**
     * {@inheritDoc}
     */
    public function getBandeja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBandeja', array());

        return parent::getBandeja();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadEsperada($cantidadEsperada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadEsperada', array($cantidadEsperada));

        return parent::setCantidadEsperada($cantidadEsperada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadEsperada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadEsperada', array());

        return parent::getCantidadEsperada();
    }

}
