<?php

namespace Proxies\__CG__\Almacigos\VentaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NotaVenta extends \Almacigos\VentaBundle\Entity\NotaVenta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'id', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'numero', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'notas', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'datosDespacho', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'fechaAbono', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'abono', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'fechaEmision', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'neto', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'iva', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'total', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'cliente', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'pedidos', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'condicionVenta');
        }

        return array('__isInitialized__', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'id', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'numero', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'notas', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'datosDespacho', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'fechaAbono', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'abono', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'fechaEmision', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'neto', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'iva', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'total', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'cliente', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'pedidos', '' . "\0" . 'Almacigos\\VentaBundle\\Entity\\NotaVenta' . "\0" . 'condicionVenta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NotaVenta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotas($notas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotas', array($notas));

        return parent::setNotas($notas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotas', array());

        return parent::getNotas();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatosDespacho($datosDespacho)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatosDespacho', array($datosDespacho));

        return parent::setDatosDespacho($datosDespacho);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosDespacho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosDespacho', array());

        return parent::getDatosDespacho();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAbono($fechaAbono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAbono', array($fechaAbono));

        return parent::setFechaAbono($fechaAbono);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAbono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAbono', array());

        return parent::getFechaAbono();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbono($abono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbono', array($abono));

        return parent::setAbono($abono);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbono', array());

        return parent::getAbono();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEmision($fechaEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEmision', array($fechaEmision));

        return parent::setFechaEmision($fechaEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEmision', array());

        return parent::getFechaEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeto($neto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeto', array($neto));

        return parent::setNeto($neto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeto', array());

        return parent::getNeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', array($iva));

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', array());

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function addPedido(\Almacigos\VentaBundle\Entity\Pedido $pedidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPedido', array($pedidos));

        return parent::addPedido($pedidos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePedido(\Almacigos\VentaBundle\Entity\Pedido $pedidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePedido', array($pedidos));

        return parent::removePedido($pedidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPedidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedidos', array());

        return parent::getPedidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\Almacigos\VentaBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondicionVenta(\Almacigos\VentaBundle\Entity\CondicionVenta $condicionVenta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondicionVenta', array($condicionVenta));

        return parent::setCondicionVenta($condicionVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondicionVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondicionVenta', array());

        return parent::getCondicionVenta();
    }

}
